### ISSUE TITLE
`lyrebird-audiotools` is not compatible with `python >= 3.11`?

### ISSUE THREAD

**Issue by iyaja** [descriptinc/audiotools#77]
Got this error when running `pip install -e .` in a fresh environment with Python 3.11.

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-q3vbs1l8/numba_ae5d20cfb46e4636ac3a597b9d8d7f0e/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-q3vbs1l8/numba_ae5d20cfb46e4636ac3a597b9d8d7f0e/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.3; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by scottbreyfogle** [comment]
3.11 is now included in tests and appears to work. The runners did not have access to 3.12 or 3.13, so I can't say for those.
